[package]
name = "gdalsource-process-bench"
version.workspace = true
authors.workspace = true
edition.workspace = true
publish.workspace = true
license-file.workspace = true
documentation.workspace = true
repository.workspace = true

[[bench]]
name = "gdal_source_operator_bench"
harness = false

[dependencies]
geoengine-operators = { path = "..", default-features = false, features = ["gdalsource-process"] }
geoengine-datatypes = { path = "../../datatypes" }
criterion = { workspace = true }
rand = { workspace = true, features = ["small_rng"] }
futures = { workspace = true }
tokio = { workspace = true }
rayon = { workspace = true }

[lints]
workspace = true