[package]
name = "geoengine-datatypes"
version = "0.1.0"
authors = [
    "Christian Beilschmidt <beilschmidt@mathematik.uni-marburg.de>",
    "Johannes Drönner <droenner@mathematik.uni-marburg.de>",
    "Michael Mattig <mattig@mathematik.uni-marburg.de>"
]
edition = "2018"

[dependencies]
arrow = "0.16" # simd compiles with nightly only
float-cmp = "0.6"
geo = "0.12"
ocl = "0.19"
serde = { version = "1.0", features = ["derive"] }
snafu = "0.6"

[dev-dependencies]
criterion = "0.3"
serde_json = "1.0"

[[bench]]
name = "point_collection"
harness = false
