[package]
name = "geoengine-datatypes"
version = "0.1.0"
authors = [
    "Christian Beilschmidt <beilschmidt@mathematik.uni-marburg.de>",
    "Johannes Drönner <droenner@mathematik.uni-marburg.de>",
    "Michael Mattig <mattig@mathematik.uni-marburg.de>"
]
edition = "2018"

[dependencies]
float-cmp = "0.6"
geo = "0.12"
serde = { version = "1.0", features = ["derive"] }
snafu = "0.6"
