[package]
name = "geoengine-services"
version = "0.1.0"
authors = [
    "Christian Beilschmidt <beilschmidt@mathematik.uni-marburg.de>",
    "Johannes Drönner <droenner@mathematik.uni-marburg.de>",
    "Michael Mattig <mattig@mathematik.uni-marburg.de>"
]
edition = "2018"

[dependencies]
geoengine-datatypes = { git = "https://github.com/geo-engine/datatypes" } # TODO: Use version when available
geoengine-operators = { git = "https://github.com/geo-engine/operators" } # TODO: Use version when available

tokio = { version = "0.2", features = ["macros"] }
warp = "0.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
uuid = { version = "0.8", features = ["serde", "v4", "v5"] }
snafu = "0.6"
pwhash = "0.3.0"
chrono = { version = "0.4", features = ["serde"] }
