

syntax = "proto3";

import "google/protobuf/any.proto";

package gdal_dataset_service;

service GdalDatasetService {
    rpc LoadTileData (GdalDatasetParameters) returns (TileDataReply) {};
}

    // pub file_path: PathBuf,
    // pub rasterband_channel: usize,
    // pub geo_transform: GdalDatasetGeoTransform, // TODO: discuss if we need this at all
    // pub width: usize,
    // pub height: usize,
    // pub file_not_found_handling: FileNotFoundHandling,
    // #[serde(default)]
    // #[serde(with = "float_option_with_nan")]
    // pub no_data_value: Option<f64>,
    // pub properties_mapping: Option<Vec<GdalMetadataMapping>>,
    // // Dataset open option as strings, e.g. `vec!["UserPwd=geoengine:pwd".to_owned(), "HttpAuth=BASIC".to_owned()]`
    // pub gdal_open_options: Option<Vec<String>>,
    // // Configs as key, value pairs that will be set as thread local config options, e.g.
    // // `vec!["AWS_REGION".to_owned(), "eu-central-1".to_owned()]` and unset afterwards
    // // TODO: validate the config options: only allow specific keys and specific values
    // pub gdal_config_options: Option<Vec<(String, String)>>,
    // #[serde(default)]
    // pub allow_alphaband_as_mask: bool,
    // pub retry: Option<GdalRetryOptions>,


enum FileNotFoundHandling {
  NoData = 0;
  Error = 1;
}

message GdalDatasetParameters {
  string file_path = 1; 
  uint32 rasterband_channel = 2;
  // geo transform
  uint32 width = 4;
  uint32 height = 5;
  FileNotFoundHandling file_not_found_handling = 6;
  // option double no_data_value = 7; // option is behaving weird
  // some mapping = 8
  // some options = 9;
  // some configs = 10;
  bool allow_alphaband_as_mask = 11;
  // retry options = 12;
}

// for now just info about the success
message TileDataReply {
  bool success = 1;
  uint32 data_size = 2;
  bytes ipc_data = 3;
}
