[package]
name = "geoengine-macros" # having a dash in the name breaks test runner codelense in rust analyzer
version = "0.1.0"
edition = "2021"


[lib]
proc-macro = true

[features]
pro = []

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = "2.0"
