
[package]
name = "gdalprocess"
version.workspace = true
authors.workspace = true
edition.workspace = true
publish.workspace = true
license-file.workspace = true
documentation.workspace = true
repository.workspace = true

[lib] # some lib that is currently empty
name = "libgdalprocess"
path = "src/lib.rs"

[[bin]] # Bin to run the gRPC server
name = "gdalprocess"
path = "src/main.rs"

[[bin]] # Bin to run the gRPC client
name = "gdalprocess-client"
path = "src/client.rs"

#######################################################################################

[[bin]] # Bin to run the arrow-flight-client
name = "gdalprocess-arrow-client"
path = "src/arrow_client.rs"

[[bin]] # Bin to run the arrow-flight-server
name = "gdalprocess-arrow-server"
path = "src/arrow_server.rs"

#######################################################################################

[[bin]] # Bin to run the ipc-channel client
name = "gdalprocess-ipc-channel-client"
path = "src/ipc-client-main.rs"

[[bin]] # Bin to run the ipc-channel server
name = "gdalprocess-ipc-channel-server"
path = "src/ipc-server-main.rs"

#### for benchmarks ###################################################################

[[bin]] # Bin to run the ipc-channel server
name = "gdalprocess-grpc-bench-server"
path = "src/grpc_server_main.rs"

#######################################################################################

[[bench]]
name = "ipc_channel_bench"
harness = false

[[bench]]
name = "ipc_channel_process_bench"
harness = false

[[bench]]
name = "grpc_process_bench"
harness = false

[[bench]]
name = "grpc_bench"
harness = false
 
 ######################################################################################

# copied from operators ( then modified )
[dependencies]

geoengine-operators = { path = "../operators" }

arrow = { workspace = true }
arrow-flight = { workspace = true }
arrow-schema = { workspace = true }
arrow-array = { workspace = true }

prost = { version = "0.14" }
prost-types = { version = "0.14" }
tonic = { version = "0.14" }
tonic-prost = { version = "0.14" }

ipc-channel = { workspace = true }
criterion = { workspace = true }
rand = { workspace = true }

async-trait = { workspace = true }
bb8-postgres = { workspace = true }
bytes = { workspace = true }
chrono = { workspace = true }
csv = { workspace = true }
float-cmp = { workspace = true }
futures = { workspace = true }
gdal = { workspace = true }
gdal-sys = { workspace = true }
geo = { workspace = true }
geoengine-datatypes = { path = "../datatypes" }
geoengine-expression = { path = "../expression" }
itertools = { workspace = true }
libloading = { workspace = true }
tracing = { workspace = true }
lru = { workspace = true }
lz4_flex = { workspace = true }
ndarray = { workspace = true }
num-traits = { workspace = true }
num = { workspace = true }
ouroboros = { workspace = true }
ordered-float = { workspace = true }
ort = { workspace = true }
paste = { workspace = true }
pin-project = { workspace = true }
postgres-protocol = { workspace = true }
postgres-types = { workspace = true }
rayon = { workspace = true }
rustc-hash = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
snafu = { workspace = true }
stream-cancel = { workspace = true }
tempfile = { workspace = true }
tokio = { workspace = true }
tokio-postgres = { workspace = true }
typetag = { workspace = true }
uuid = { workspace = true }
strum = { workspace = true }

[build-dependencies]
tonic-prost-build = "*" # TODO (low): fix version

[dev-dependencies]

async-stream = { workspace = true }

approx = { workspace = true }
geo-rand = { workspace = true }
httptest = { workspace = true }
tracing-subscriber = { workspace = true, features = ["json"] }
rand = { workspace = true, features = ["small_rng"] }

[lints]
workspace = true

