
[package]
name = "gdalprocess"
version.workspace = true
authors.workspace = true
edition.workspace = true
publish.workspace = true
license-file.workspace = true
documentation.workspace = true
repository.workspace = true

#### bins -- for benchmarks ###########################################################

#### bins -- for actual reading #######################################################

[[bin]] # Bin to run the ipc-channel server; serialises data at each request with bincode / serde
name = "gdalsource-process"
path = "bin/gdalsource_process_main.rs"

#### -- bneches #######################################################################

[[bench]]
name = "gdal_source_process_bench"
harness = false

[[bench]]
name = "gdal_source_operator_bench"
harness = false

######################################################################################

# copied from operators ( then modified )
# TODO go over those and remove what we dont need
[dependencies]

geoengine-operators = { path = "../operators" }
# geoengine-operators-new = {
#    path = "../operators",
#    package = "geoengine-operators" ,
#    features = ["gdalsource-process"]
# }

arrow = { workspace = true }
arrow-flight = { workspace = true }
arrow-schema = { workspace = true }
arrow-array = { workspace = true }

bincode = { version = "2.0.1", features = ["derive", "serde"] }

ipc-channel = { workspace = true }
criterion = { workspace = true }
rand = { workspace = true }

async-trait = { workspace = true }
bb8-postgres = { workspace = true }
bytes = { workspace = true }
chrono = { workspace = true }
csv = { workspace = true }
float-cmp = { workspace = true }
futures = { workspace = true }
gdal = { workspace = true }
gdal-sys = { workspace = true }
geo = { workspace = true }
geoengine-datatypes = { path = "../datatypes" }
geoengine-expression = { path = "../expression" }
itertools = { workspace = true }
libloading = { workspace = true }
tracing = { workspace = true }
lru = { workspace = true }
lz4_flex = { workspace = true }
ndarray = { workspace = true }
num-traits = { workspace = true }
num = { workspace = true }
ouroboros = { workspace = true }
ordered-float = { workspace = true }
ort = { workspace = true }
paste = { workspace = true }
pin-project = { workspace = true }
postgres-protocol = { workspace = true }
postgres-types = { workspace = true }
rayon = { workspace = true }
rustc-hash = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
snafu = { workspace = true }
stream-cancel = { workspace = true }
tempfile = { workspace = true }
tokio = { workspace = true }
tokio-postgres = { workspace = true }
typetag = { workspace = true }
uuid = { workspace = true }
strum = { workspace = true }

[dev-dependencies]
async-stream = { workspace = true }

approx = { workspace = true }
geo-rand = { workspace = true }
httptest = { workspace = true }
tracing-subscriber = { workspace = true, features = ["json"] }
rand = { workspace = true, features = ["small_rng"] }

[lints]
workspace = true
