
.PHONY: arrow-server
arrow-server:
	@echo "Running Arrow Server..."
	cargo run --bin gdalprocess-arrow-server

.PHONY: arrow-client
arrow-client:
	@echo "Running Arrow Client..."
	cargo run --bin gdalprocess-arrow-client

.PHONY: server
server:
	@echo "Running Server..."
	cargo run --bin gdalprocess

.PHONY: arrow-client
client:
	@echo "Running Client..."
	cargo run --bin gdalprocess-client

