
.PHONY: arrow-server
arrow-server:
	@echo "Running Arrow Server..."
	cargo run --bin gdalprocess-arrow-server

.PHONY: arrow-client
arrow-client:
	@echo "Running Arrow Client..."
	cargo run --bin gdalprocess-arrow-client

.PHONY: arrow-server
arrow-server:
	@echo "Running Server..."
	cargo run --bin gdalprocess

.PHONY: arrow-client
arrow-client:
	@echo "Running Client..."
	cargo run --bin gdalprocess-client

.PHONY: ipc-client
ipc-client:
	@echo "Running Client..."
	cargo run --bin gdalprocess-ipc-channel-client

.PHONY: ipc-server
ipc-server:
	@echo "Running Server..."
	cargo run --bin gdalprocess-ipc-channel-server

