[package]
name = "geoengine-operators"
version = "0.1.0"
authors = [
    "Christian Beilschmidt <beilschmidt@mathematik.uni-marburg.de>",
    "Johannes Drönner <droenner@mathematik.uni-marburg.de>",
    "Michael Mattig <mattig@mathematik.uni-marburg.de>"
]
edition = "2018"

[dependencies]
csv = "1.1"
geoengine-datatypes = { path = "../datatypes" }
float-cmp = "0.6"
futures = "0.3"
geo = "0.12"
ocl = "0.19"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
snafu = "0.6"

[dev-dependencies]
criterion = "0.3"
tempfile = "3.1"
