name: Rust

on: [push, pull_request]

jobs:
  build:

    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os:
          - ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          components: clippy
          override: true
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features
      - name: Install OpenCL
        run: |
          sudo apt-get install ocl-icd-opencl-dev pocl-opencl-icd
          sudo ln -s /usr/lib/llvm-6.0/lib/clang/6.0.1 /usr/lib/llvm-6.0/lib/clang/6.0.0
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
